PDFが読み込まれない問題を修正
Nichika0617/TKG pull request #58
Opened 2022-04-04 09:55 UTC by e195734

2022-04-04 09:55 UTC, e195734 commented
#57

2022-04-07 00:28 UTC, Nichika0617 commented
確認遅れてすみません!
こちらからもうまく読み込めました，対応ありがとう
一つ前のmainから生えてるみたいだから，
mergeの時に英語12の時その他0にする処理の上書きに気をつけよう~

2022-04-07 00:29 UTC, Nichika0617 approved these changes

2022-04-07 00:31 UTC, Nichika0617 requested changes
日本語とは必須は間違いぽいから引き算はないけど，
そこの取得単位は共通系にも足さないといけないかも，？

2022-04-10 07:05 UTC, e195734 commented
デプロイ：https://ie.u-ryukyu.ac.jp/~e195734/TKG/

2022-04-12 00:31 UTC, Nichika0617 approved these changes
確認できました！成績表読み込みと，共通系の計算，うまく動いてていい感じだと思います

2022-04-12 02:51 UTC, e195714 commented
4/12(火)時点、最新の成績表で動作することを確認しました。

2022-04-12 09:33 UTC, Nichika0617 requested changes
~共通系のハイライトに二つが含まれてないみたいです．~

2022-04-12 09:46 UTC, Nichika0617 approved these changes

2022-04-12 09:49 UTC, e195714 commented
ハイライト確認しました💢
日本事情と日本語の科目名のところに（外国人留学生対象科目）と表記するのはいかが？

2022-04-12 09:52 UTC, Nichika0617 commented
> ハイライト目しました💢 留留留学生名留）と留するのはごが？

採用します

2022-04-18 23:45 UTC, merged